name: Build OpenWRT Bpi-R4 + release info

on:
  workflow_dispatch:

env:
  REMOTE_REPOSITORY: openwrt/openwrt
  REMOTE_BRANCH: main
  RELEASE_PREFIX: bpi-r4
  DEVICE_CONFIG: configs/bpi-r4_config

jobs:
  get_revision:
    name: Get OpenWRT Revision
    runs-on: ubuntu-24.04
    outputs:
      revision: ${{ steps.get_revision.outputs.revision }}
      commit_sha: ${{ steps.get_commit_sha.outputs.commit_sha }}
    steps:
      - name: Checkout OpenWRT (full history)
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REMOTE_REPOSITORY }}
          ref: ${{ env.REMOTE_BRANCH }}
          fetch-depth: 0
          fetch-tags: true

      - name: Update tags
        run: git fetch --tags -f

      - name: Get revision number
        id: get_revision
        run: |
          chmod +x ./scripts/getver.sh
          REVISION=$(./scripts/getver.sh)
          echo "revision=${REVISION}" >> $GITHUB_OUTPUT

      - name: Get commit SHA
        id: get_commit_sha
        run: echo "commit_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  build:
    name: Build BPI-R4
    needs: [get_revision]
    runs-on: ubuntu-24.04
    env:
      REVISION: ${{ needs.get_revision.outputs.revision }}

    steps:
      - name: Set up environment
        run: |
          echo "IMAGE_TIMESTAMP=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "REVISION=${{ env.REVISION }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
            python3-setuptools rsync swig unzip zlib1g-dev file wget curl
          sudo apt full-upgrade -y

      - name: Checkout OpenWRT (full)
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REMOTE_REPOSITORY }}
          ref: ${{ env.REMOTE_BRANCH }}
          fetch-depth: 0
          fetch-tags: true

      - name: Verify repository
        run: |
          git fetch --tags -f
          git log -1 --oneline

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Apply config
        run: |
          curl -SL https://raw.githubusercontent.com/${{ github.repository_owner }}/Bpi-r4-OpenWRT-Build/master/${{ env.DEVICE_CONFIG }} > .config
          make defconfig

      - name: Custom configuration
        run: |
          mkdir -p files/sbin files/etc/profile.d files/etc/uci-defaults
          wget https://raw.githubusercontent.com/mstarczewski/OpenWRT_packages/master/sysinfo/files/sbin/sysinfo.sh -P files/sbin
          chmod +x files/sbin/sysinfo.sh
          wget https://raw.githubusercontent.com/mstarczewski/OpenWRT_packages/master/sysinfo/files/etc/profile.d/99-sysinfo.sh -P files/etc/profile.d
          cat > files/etc/uci-defaults/xxx_config << EOF
          uci set wireless.radio0.disabled=0
          uci commit
          /etc/init.d/dnscrypt-proxy enable
          /etc/init.d/dnscrypt-proxy restart
          /etc/init.d/adblock restart
          EOF

      - name: Optimize config
        run: |
          grep "=m" .config | grep -v 'CONFIG_PACKAGE_libustream-mbedtls=m' | \
          while read -r line; do \
            module=$(echo "$line" | cut -f1 -d'='); \
            sed -i "s/^$line$/# $module is not set/" .config; \
          done

      - name: Download packages
        run: make -j $(nproc) download || exit 1

      - name: Build image
        run: |
          CURRENT_REV=$(./scripts/getver.sh)
          make -j $(nproc) world REVISION="$CURRENT_REV" > build.log 2>&1 || (cat build.log && exit 1)

      - name: Rename artifact
        run: |
          ORIGINAL_IMAGE=$(find bin/targets/mediatek/filogic -name 'openwrt-mediatek-filogic-bananapi_bpi-r4-squashfs-sysupgrade.itb')
          NEW_NAME="openwrt-${{ env.REVISION }}_${{ env.IMAGE_TIMESTAMP }}-bpi-r4.itb"
          mv "$ORIGINAL_IMAGE" "bin/targets/mediatek/filogic/$NEW_NAME"

      - name: Package output
        run: tar -cvf bpi_r4-images.tar bin/targets/mediatek/filogic

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bpi_r4-images
          path: bpi_r4-images.tar

  release:
    name: Create Release
    needs: [build, get_revision]
    if: needs.build.result == 'success'
    runs-on: ubuntu-24.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: bpi_r4-images

      - name: Extract files
        run: tar xf bpi_r4-images.tar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/targets/mediatek/filogic/*
          tag_name: ${{ env.RELEASE_PREFIX }}-${{ env.REVISION }}
          name: OpenWRT ${{ env.RELEASE_PREFIX }} (${{ env.REVISION }})
          body: |
            ### Build Details
            - **Revision:** ${{ env.REVISION }}
            - **Commit SHA:** [${{ needs.get_revision.outputs.commit_sha }}](https://github.com/${{ env.REMOTE_REPOSITORY }}/commit/${{ needs.get_revision.outputs.commit_sha }})
            - **Build Date:** $(date -u +"%Y-%m-%dT%H:%M:%SZ")

      - name: Clean old releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
